In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
df = pd.read_excel('s3://proyectosandratamayo/BuenaventuraySanAndTumacmesxmes.xlsx')

In [3]:
#df = pd.read_excel('/content/drive/MyDrive/Proyecto investigación/BuenaventuraySanAndTumacmesxmes.xlsx')

In [6]:
df

Código DANE de Municipio   Año  Mes       cruce  \
0                       52835  2003    1  5283520031   
1                       52835  2003    2  5283520032   
2                       52835  2003    3  5283520033   
3                       52835  2003    4  5283520034   
4                       52835  2003    5  5283520035   
..                        ...   ...  ...         ...   
461                     76109  2022    1  7610920221   
462                     76109  2022    2  7610920222   
463                     76109  2022    3  7610920223   
464                     76109  2022    4  7610920224   
465                     76109  2022    5  7610920225   

     Victconf_Desplazamiento forzado  Cant_acc_subversivas  \
0                                115                     0   
1                                148                     1   
2                                120                     0   
3                                 74                     0   
4                                 91                     1   
..                               ...                   ...   
461                             2558                     0   
462                             2003                     0   
463                             1299                     0   
464                             1502                     0   
465                              732                     0   

     Cant_acc_terroristas  Cant_atenta_pte_vias  Cant_delito_med_ambiente  \
0                       0                     0                         0   
1                       0                     0                         0   
2                       0                     0                         0   
3                       0                     0                         0   
4                       0                     0                         0   
..                    ...                   ...                       ...   
461                     0                     0                         0   
462                     0                     0                         2   
463                     0                     0                         0   
464                     0                     0                         2   
465                     0                     0                         2   

     Cant_delito_sexual  ...  Victconf_Delitointegridadsexual  \
0                     0  ...                                2   
1                     1  ...                                0   
2                     0  ...                                1   
3                     0  ...                                1   
4                     0  ...                                2   
..                  ...  ...                              ...   
461                   3  ...                                2   
462                   6  ...                                4   
463                  11  ...                                5   
464                  14  ...                                5   
465                   2  ...                                2   

     Victconf_Desaparición forzada  Victconf_Homicidio  \
0                                3                  27   
1                                3                  17   
2                                4                  26   
3                                3                  24   
4                                2                  27   
..                             ...                 ...   
461                              0                   1   
462                              0                   0   
463                              0                   0   
464                              0                   1   
465                              0                   0   

     Victconf_LesionPersonalFisica  Victconf_LesionPersonalPsicolog  \
0                                0                                0   
1                                0        

## Exploracion

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466 entries, 0 to 465
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Código DANE de Municipio                466 non-null    int64
 1   Año                                     466 non-null    int64
 2   Mes                                     466 non-null    int64
 3   cruce                                   466 non-null    int64
 4   Victconf_Desplazamiento forzado         466 non-null    int64
 5   Cant_acc_subversivas                    466 non-null    int64
 6   Cant_acc_terroristas                    466 non-null    int64
 7   Cant_atenta_pte_vias                    466 non-null    int64
 8   Cant_delito_med_ambiente                466 non-null    int64
 9   Cant_delito_sexual                      466 non-null    int64
 10  Cant_extorsion                          466 non-null    int64
 11  Cant_homicidios    

In [9]:
df.describe()

Código DANE de Municipio          Año         Mes         cruce  \
count                466.000000   466.000000  466.000000  4.660000e+02   
mean               64472.000000  2012.214592    6.424893  2.064217e+10   
std                11649.506183     5.614601    3.462199  2.564621e+10   
min                52835.000000  2003.000000    1.000000  5.283520e+09   
25%                52835.000000  2007.000000    3.000000  5.283520e+09   
50%                64472.000000  2012.000000    6.000000  7.610920e+09   
75%                76109.000000  2017.000000    9.000000  7.610920e+09   
max                76109.000000  2022.000000   12.000000  7.610920e+10   

       Victconf_Desplazamiento forzado  Cant_acc_subversivas  \
count                       466.000000            466.000000   
mean                        742.562232              0.098712   
std                         836.916047              0.380885   
min                          43.000000              0.000000   
25%                         247.000000              0.000000   
50%                         513.000000              0.000000   
75%                         962.500000              0.000000   
max                        9993.000000              4.000000   

       Cant_acc_terroristas  Cant_atenta_pte_vias  Cant_delito_med_ambiente  \
count            466.000000            466.000000                466.000000   
mean               0.781116              0.124464                  1.214592   
std                2.035002              0.623520                  1.972140   
min                0.000000              0.000000                  0.000000   
25%                0.000000              0.000000                  0.000000   
50%                0.000000              0.000000                  0.000000   
75%                1.000000              0.000000                  2.000000   
max               19.000000              8.000000                 13.000000   

       Cant_delito_sexual  ...  Victconf_Delitointegridadsexual  \
count          466.000000  ...                       466.000000   
mean             4.600858  ...                         1.772532   
std              4.371403  ...                         2.116951   
min              0.000000  ...                         0.000000   
25%              1.000000  ...                         0.000000   
50%              3.000000  ...                         1.000000   
75%              8.000000  ...                         2.000000   
max             21.000000  ...                        12.000000   

       Victconf_Desaparición forzada  Victconf_Homicidio  \
count                     466.000000          466.000000   
mean                        3.716738           18.096567   
std                         5.322828           18.227750   
min                         0.000000            0.000000   
25%                         0.000000            3.000000   
50%                         1.000000           14.000000   
75%                         6.000000           28.000000   
max                        32.000000          108.000000   

       Victconf_LesionPersonalFisica  Victconf_LesionPersonalPsicolog  \
count                     466.000000                       466.000000   
mean                        0.538627                         0.253219   
std                         0.976944                         1.221774   
min                         0.000000                         0.000000   
25%                         0.000000                         0.000000   
50%                         0.000000                         0.000000   
75%                         1.000000                         0.000000   
max                        10.000000                        22.000000   

       Victconf_MinasAntipers_explos  Victconf_PerdidadeBienes  \
count                     466.000000                466.000000   
mean                        0.165236                  7.954936   
std                         0.678830              

In [10]:
df['Código DANE de Municipio'].value_counts()

52835    233
76109    233
Name: Código DANE de Municipio, dtype: int64

In [19]:
train, test = train_test_split(df, test_size = 0.3, random_state = 42,stratify = df['Código DANE de Municipio'])

In [18]:
train['Código DANE de Municipio'].value_counts()/train['Código DANE de Municipio'].count()

52835    0.5
76109    0.5
Name: Código DANE de Municipio, dtype: float64

In [17]:
test['Código DANE de Municipio'].value_counts()/test['Código DANE de Municipio'].count()

76109    0.5
52835    0.5
Name: Código DANE de Municipio, dtype: float64

In [ ]:
#train.to_csv('s3://creditdata2080/Datos/train/train.csv', index = False)

In [ ]:
#test.to_csv('s3://creditdata2080/Datos/test/train.csv',index = False)

In [14]:
#Verificar la cantidad de valores nulos en el dataset
train.isna().sum()

Código DANE de Municipio                  0
Año                                       0
Mes                                       0
cruce                                     0
Victconf_Desplazamiento forzado           0
Cant_acc_subversivas                      0
Cant_acc_terroristas                      0
Cant_atenta_pte_vias                      0
Cant_delito_med_ambiente                  0
Cant_delito_sexual                        0
Cant_extorsion                            0
Cant_homicidios                           0
Cant_homicid_colect                       0
Cant_lesiones_personales                  0
Cant_pirateria_terrestre                  0
Cant_secuestros                           0
Victconf_AbandoDespojForzTierras          0
Victconf_Actoterrorista                   0
Victconf_Amenaza                          0
Victconf_Confinamiento                    0
Victconf_Delitointegridadsexual           0
Victconf_Desaparición forzada             0
Victconf_Homicidio              

In [15]:
train.columns.unique()

Index(['Código DANE de Municipio', 'Año', 'Mes', 'cruce',
       'Victconf_Desplazamiento forzado', 'Cant_acc_subversivas',
       'Cant_acc_terroristas', 'Cant_atenta_pte_vias',
       'Cant_delito_med_ambiente', 'Cant_delito_sexual', 'Cant_extorsion',
       'Cant_homicidios', 'Cant_homicid_colect', 'Cant_lesiones_personales',
       'Cant_pirateria_terrestre', 'Cant_secuestros',
       'Victconf_AbandoDespojForzTierras', 'Victconf_Actoterrorista',
       'Victconf_Amenaza', 'Victconf_Confinamiento',
       'Victconf_Delitointegridadsexual', 'Victconf_Desaparición forzada',
       'Victconf_Homicidio', 'Victconf_LesionPersonalFisica',
       'Victconf_LesionPersonalPsicolog', 'Victconf_MinasAntipers_explos',
       'Victconf_PerdidadeBienes', 'Victconf_Secuestro', 'Victconf_Tortura',
       'Victconf_Vinculacde Niños NiñasyAdoles'],
      dtype='object')

In [16]:
#Cantidad de reuniones por grupo
train.groupby(['Código DANE de Municipio']).size().reset_index(name='cantidad de registros')

Código DANE de Municipio  cantidad de registros
0                     52835                    163
1                     76109                    163

In [20]:
#Cantidad de reuniones por grupo
train.groupby(['Código DANE de Municipio','Victconf_Desplazamiento forzado']).size().reset_index(name='cantidad de registros')

Código DANE de Municipio  Victconf_Desplazamiento forzado  \
0                       52835                               62   
1                       52835                               64   
2                       52835                               73   
3                       52835                               74   
4                       52835                               80   
..                        ...                              ...   
295                     76109                             3524   
296                     76109                             3806   
297                     76109                             4162   
298                     76109                             5738   
299                     76109                             5862   

     cantidad de registros  
0                        1  
1                        1  
2                        1  
3                        2  
4                        1  
..                     ...  
295                      1  
296                      1  
297                      1  
298                      1  
299                      1  

[300 rows x 3 columns]

In [ ]:
pd.crosstab(index=train['Código DANE de Municipio'], columns=train['Victconf_Desplazamiento forzado'], margins =True)

In [ ]:
tabla_dpto=pd.crosstab(index=train['Código DANE de Municipio'], columns=train['Victconf_Desplazamiento forzado'], margins =True)

In [ ]:
tabla_dpto

In [ ]:
tabla_sex['probabilidad'] = tabla_sex.iloc[:,1]/tabla_sex.iloc[:,2]

In [ ]:
tabla_sex

Risk    bad  good  All  probabilidad
Sex                                 
female   76   138  214       0.64486
male    134   352  486       0.72428
All     210   490  700       0.70000

## Preprocesamiento

## Imputación

In [15]:
from sklearn.impute import SimpleImputer
import numpy as np

In [21]:
X_train = train[['Victconf_Desplazamiento forzado', 'Cant_acc_subversivas',
       'Cant_acc_terroristas', 'Cant_atenta_pte_vias',
       'Cant_delito_med_ambiente', 'Cant_delito_sexual', 'Cant_extorsion',
       'Cant_homicidios', 'Cant_homicid_colect', 'Cant_lesiones_personales',
       'Cant_pirateria_terrestre', 'Cant_secuestros',
       'Victconf_AbandoDespojForzTierras', 'Victconf_Actoterrorista',
       'Victconf_Amenaza', 'Victconf_Confinamiento',
       'Victconf_Delitointegridadsexual', 'Victconf_Desaparición forzada',
       'Victconf_Homicidio', 'Victconf_LesionPersonalFisica',
       'Victconf_LesionPersonalPsicolog', 'Victconf_MinasAntipers_explos',
       'Victconf_PerdidadeBienes', 'Victconf_Secuestro', 'Victconf_Tortura',
       'Victconf_Vinculacde Niños NiñasyAdoles']]

In [22]:
imputer = SimpleImputer(strategy = 'mean')

In [23]:
imputer.statistics_

AttributeError: ignored

In [24]:
X_train['Victconf_Desplazamiento forzado'].mean()

729.7269938650306

In [ ]:
imputer.transform([[24,100,np.nan], [np.nan,np.nan,12]])

In [ ]:
imputer.fit_transform(X_train)

In [ ]:
X_train = train[['Saving accounts', 'Checking account']]

In [ ]:
imputer = SimpleImputer(strategy = 'most_frequent')

In [ ]:
imputer.fit(X_train)

In [ ]:
imputer.statistics_

In [ ]:
imputer.fit_transform(X_train)

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
imputer = KNNImputer(n_neighbors = 2)

In [ ]:
df2 = pd.DataFrame([[40, 19, 3], [42,20,3.1], [44,21,np.nan], [45,23,4.1], [39,25, 5.0], [80,27,np.nan], [82,3.0,4.8]], columns=["Peso", "Edad", "nota"])

In [ ]:
df2

In [ ]:
result = imputer.fit_transform(df2)

In [ ]:
result

## Escalada

In [16]:
from sklearn.preprocessing import StandardScaler, RobustScaler

In [17]:
scaler = StandardScaler()

In [31]:
scaler.fit(X_train[['Victconf_Desplazamiento forzado','Cant_acc_subversivas']])

StandardScaler()

In [32]:
scaler.mean_

array([7.29726994e+02, 1.07361963e-01])

In [33]:
scaler.var_**0.5

array([7.65029449e+02, 4.11649127e-01])

In [36]:
scaler.transform(X_train[['Victconf_Desplazamiento forzado','Cant_acc_subversivas']])

array([[-2.97073451e-02,  2.16844389e+00],
       [-5.93084351e-01, -2.60809403e-01],
       [-1.61728407e-01, -2.60809403e-01],
       [ 5.99026622e-01, -2.60809403e-01],
       [-4.06163442e-01, -2.60809403e-01],
       [ 1.06235134e-01, -2.60809403e-01],
       [ 5.06219737e-01, -2.60809403e-01],
       [-1.34278483e-01, -2.60809403e-01],
       [-3.34270784e-01, -2.60809403e-01],
       [-7.76083842e-01, -2.60809403e-01],
       [ 5.31055382e-01, -2.60809403e-01],
       [ 5.57198167e-01,  2.16844389e+00],
       [ 1.08139708e-02, -2.60809403e-01],
       [-8.57126474e-01, -2.60809403e-01],
       [-2.25742142e-03, -2.60809403e-01],
       [-7.15358003e-02, -2.60809403e-01],
       [-8.04840905e-01, -2.60809403e-01],
       [-4.14006277e-01, -2.60809403e-01],
       [-8.03533766e-01, -2.60809403e-01],
       [ 9.36268542e-01, -2.60809403e-01],
       [-5.63020149e-01, -2.60809403e-01],
       [-3.93092049e-01, -2.60809403e-01],
       [ 5.26424260e-02, -2.60809403e-01],
       [ 6.

In [30]:
scaler.inverse_transform([[-7.09419742e-01]])

array([[186.99999975]])

In [ ]:
#Robust scaler
X_train['Age'].quantile(0.5)

33.0

In [ ]:
median = X_train['Age'].median()

In [ ]:
q1 = X_train['Age'].quantile(0.25)

In [ ]:
q3 = X_train['Age'].quantile(0.75)