In [74]:
import pandas as pd
from sklearn.model_selection import train_test_split
import joblib

In [75]:
df = pd.read_csv('s3://creditdata2080/Datos/Original/german_credit_data.csv')

In [76]:
df

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0             0   67    male    2     own             NaN           little   
1             1   22  female    2     own          little         moderate   
2             2   49    male    1     own          little              NaN   
3             3   45    male    2    free          little           little   
4             4   53    male    2    free          little           little   
..          ...  ...     ...  ...     ...             ...              ...   
995         995   31  female    1     own          little              NaN   
996         996   40    male    3     own          little           little   
997         997   38    male    2     own          little              NaN   
998         998   23    male    2    free          little           little   
999         999   27    male    2     own        moderate         moderate   

     Credit amount  Duration              Purpose  Risk  
0             1169         6             radio/TV  good  
1             5951        48             radio/TV   bad  
2             2096        12            education  good  
3             7882        42  furniture/equipment  good  
4             4870        24                  car   bad  
..             ...       ...                  ...   ...  
995           1736        12  furniture/equipment  good  
996           3857        30                  car  good  
997            804        12             radio/TV  good  
998           1845        45             radio/TV   bad  
999           4576        45                  car  good  

[1000 rows x 11 columns]

## Exploracion

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        1000 non-null   int64 
 1   Age               1000 non-null   int64 
 2   Sex               1000 non-null   object
 3   Job               1000 non-null   int64 
 4   Housing           1000 non-null   object
 5   Saving accounts   817 non-null    object
 6   Checking account  606 non-null    object
 7   Credit amount     1000 non-null   int64 
 8   Duration          1000 non-null   int64 
 9   Purpose           1000 non-null   object
 10  Risk              1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB


In [78]:
df.describe()

Unnamed: 0          Age          Job  Credit amount     Duration
count  1000.000000  1000.000000  1000.000000    1000.000000  1000.000000
mean    499.500000    35.546000     1.904000    3271.258000    20.903000
std     288.819436    11.375469     0.653614    2822.736876    12.058814
min       0.000000    19.000000     0.000000     250.000000     4.000000
25%     249.750000    27.000000     2.000000    1365.500000    12.000000
50%     499.500000    33.000000     2.000000    2319.500000    18.000000
75%     749.250000    42.000000     2.000000    3972.250000    24.000000
max     999.000000    75.000000     3.000000   18424.000000    72.000000

In [79]:
df['Risk'].value_counts()

good    700
bad     300
Name: Risk, dtype: int64

In [80]:
train, test = train_test_split(df, test_size = 0.3, random_state = 42,stratify = df['Risk'])

In [81]:
train['Risk'].value_counts()/train['Risk'].count()

good    0.7
bad     0.3
Name: Risk, dtype: float64

In [82]:
test['Risk'].value_counts()/test['Risk'].count()

good    0.7
bad     0.3
Name: Risk, dtype: float64

In [83]:
train.to_csv('s3://creditdata2080/Datos/train/train.csv', index = False)

In [84]:
test.to_csv('s3://creditdata2080/Datos/test/train.csv',index = False)

In [85]:
#Verificar la cantidad de valores nulos en el dataset
train.isna().sum()

Unnamed: 0            0
Age                   0
Sex                   0
Job                   0
Housing               0
Saving accounts     125
Checking account    274
Credit amount         0
Duration              0
Purpose               0
Risk                  0
dtype: int64

In [86]:
#Cantidad de reuniones por grupo
train.groupby(['Risk']).size().reset_index(name='cantidad de reuniones por grupo')

Risk  cantidad de reuniones por grupo
0   bad                              210
1  good                              490

In [87]:
#Cantidad de reuniones por grupo
train.groupby(['Risk','Sex']).size().reset_index(name='cantidad de reuniones por grupo')

Risk     Sex  cantidad de reuniones por grupo
0   bad  female                               76
1   bad    male                              134
2  good  female                              138
3  good    male                              352

In [88]:
#Cantidad de reuniones por grupo
train.groupby(['Sex']).size().reset_index(name='cantidad de reuniones por grupo')

Sex  cantidad de reuniones por grupo
0  female                              214
1    male                              486

In [89]:
#Cantidad de reuniones por grupo
train.groupby(['Age','Risk']).size().reset_index(name='cantidad de reuniones por grupo')

Age  Risk  cantidad de reuniones por grupo
0    20   bad                                3
1    20  good                                8
2    21   bad                                3
3    21  good                                5
4    22   bad                                9
..  ...   ...                              ...
89   68   bad                                2
90   68  good                                1
91   70  good                                1
92   74  good                                1
93   75  good                                2

[94 rows x 3 columns]

In [90]:
pd.crosstab(index=train['Housing'], columns=train['Risk'], margins =True)

Risk     bad  good  All
Housing                
free      29    45   74
own      133   371  504
rent      48    74  122
All      210   490  700

In [91]:
tabla_sex=pd.crosstab(index=train['Sex'], columns=train['Risk'], margins =True)

In [92]:
tabla_sex

Risk    bad  good  All
Sex                   
female   76   138  214
male    134   352  486
All     210   490  700

In [93]:
tabla_sex['probabilidad'] = tabla_sex.iloc[:,1]/tabla_sex.iloc[:,2]

In [94]:
tabla_sex

Risk    bad  good  All  probabilidad
Sex                                 
female   76   138  214       0.64486
male    134   352  486       0.72428
All     210   490  700       0.70000

## Preprocesamiento

## Imputación

In [95]:
from sklearn.impute import SimpleImputer
import numpy as np

In [96]:
X_train = train[['Age', 'Credit amount','Duration']]

In [97]:
imputer = SimpleImputer(strategy = 'mean')

In [98]:
X_train['Age'].mean()

35.402857142857144

In [99]:
imputer.transform([[24,100,np.nan], [np.nan,np.nan,12]])

NotFittedError: This SimpleImputer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
imputer.fit_transform(X_train)

In [ ]:
X_train = train[['Saving accounts', 'Checking account']]

In [ ]:
imputer = SimpleImputer(strategy = 'most_frequent')

In [ ]:
imputer.fit(X_train)

In [ ]:
imputer.statistics_

In [ ]:
imputer.fit_transform(X_train)

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
imputer = KNNImputer(n_neighbors = 2)

In [ ]:
df2 = pd.DataFrame([[40, 19, 3], [42,20,3.1], [44,21,np.nan], [45,23,4.1], [39,25, 5.0], [80,27,np.nan], [82,3.0,4.8]], columns=["Peso", "Edad", "nota"])

In [ ]:
df2

In [ ]:
result = imputer.fit_transform(df2)

In [ ]:
result

## Escalada

In [ ]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train

In [ ]:
scaler.fit(X_train[['Age']])

In [ ]:
scaler.mean_

In [ ]:
scaler.var_**0.5

In [ ]:
scaler.transform(X_train[['Age']])

In [ ]:
scaler.inverse_transform([[-0.39189483]])

In [ ]:
#Robust scaler
X_train['Age'].quantile(0.5)

In [ ]:
median = X_train['Age'].median()

In [ ]:
q1 = X_train['Age'].quantile(0.25)

In [ ]:
q3 = X_train['Age'].quantile(0.75)

## Transformar las variables categóricas

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
encoder = OneHotEncoder(sparse=False, drop ='first')
encoder.fit_transform(train[["Sex"]])

In [ ]:
encoder.categories_

In [ ]:
encoder = OneHotEncoder(sparse=True)
encoder.fit_transform(train[["Sex"]])

In [ ]:
encoder.inverse_transform([[0]])

## Pipeline: un objeto que almacena transformaciones que hay que aplicarle a los datos

In [100]:
from sklearn.pipeline import Pipeline

In [101]:
numeric_pipeline = Pipeline(
    [
        ('Imputacion con la media', SimpleImputer(strategy = 'mean')),
        ('Escaladominmax',MinMaxScaler())
        
    ]
)

In [102]:
numeric_pipeline.fit(train[['Age','Credit amount', 'Duration']])

Pipeline(steps=[('Imputacion con la media', SimpleImputer()),
                ('Escaladominmax', MinMaxScaler())])

In [103]:
numeric_pipeline[0].statistics_

array([  35.40285714, 3236.12142857,   21.04857143])

In [104]:
numeric_pipeline[1].min_

array([-0.36363636, -0.01375592, -0.05882353])

In [105]:
numeric_pipeline[1].data_max_

array([   75., 18424.,    72.])

In [106]:
train[['Age','Credit amount', 'Duration']].max()

Age                 75
Credit amount    18424
Duration            72
dtype: int64

In [107]:
numeric_pipeline.transform(train[['Age','Credit amount', 'Duration']])

array([[0.2       , 0.23236492, 0.47058824],
       [0.47272727, 0.08688236, 0.16176471],
       [0.12727273, 0.3944096 , 0.82352941],
       ...,
       [0.78181818, 0.07730824, 0.11764706],
       [0.52727273, 0.10157368, 0.11764706],
       [0.30909091, 0.18851106, 0.02941176]])

In [108]:
numeric_pipeline.transform([[np.nan,np.nan,np.nan]])

/home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[0.28005195, 0.16430733, 0.25071429]])

In [109]:
categoric_pipeline = Pipeline(
    [
        ('Imputacion con la moda', SimpleImputer(strategy = 'most_frequent')),
        ('Codificar',OneHotEncoder(sparse=False))
        
    ]
)

In [110]:
categoric_pipeline.fit(train[['Sex','Purpose', 'Housing']])

Pipeline(steps=[('Imputacion con la moda',
                 SimpleImputer(strategy='most_frequent')),
                ('Codificar', OneHotEncoder(sparse=False))])

In [111]:
categoric_pipeline[0].statistics_

array(['male', 'car', 'own'], dtype=object)

In [112]:
categoric_pipeline[1].categories_

[array(['female', 'male'], dtype=object),
 array(['business', 'car', 'domestic appliances', 'education',
        'furniture/equipment', 'radio/TV', 'repairs', 'vacation/others'],
       dtype=object),
 array(['free', 'own', 'rent'], dtype=object)]

In [113]:
categoric_pipeline.transform(train[['Sex','Purpose', 'Housing']])

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [114]:
categoric_pipeline[1].categories_

[array(['female', 'male'], dtype=object),
 array(['business', 'car', 'domestic appliances', 'education',
        'furniture/equipment', 'radio/TV', 'repairs', 'vacation/others'],
       dtype=object),
 array(['free', 'own', 'rent'], dtype=object)]

In [115]:
from sklearn.compose import ColumnTransformer

In [116]:
column_transformer = ColumnTransformer(
    [
        ('numeric_pipeline', numeric_pipeline,[0,1,2]),
        ('categoric_pipeline',categoric_pipeline, [3,4,5])
    ])

In [117]:
column_transformer.fit(train[['Age','Credit amount', 'Duration','Sex','Purpose', 'Housing']])

ColumnTransformer(transformers=[('numeric_pipeline',
                                 Pipeline(steps=[('Imputacion con la media',
                                                  SimpleImputer()),
                                                 ('Escaladominmax',
                                                  MinMaxScaler())]),
                                 [0, 1, 2]),
                                ('categoric_pipeline',
                                 Pipeline(steps=[('Imputacion con la moda',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Codificar',
                                                  OneHotEncoder(sparse=False))]),
                                 [3, 4, 5])])

In [118]:
column_transformer.transform(train[['Age','Credit amount', 'Duration','Sex','Purpose', 'Housing']])

array([[0.2       , 0.23236492, 0.47058824, ..., 0.        , 1.        ,
        0.        ],
       [0.47272727, 0.08688236, 0.16176471, ..., 0.        , 1.        ,
        0.        ],
       [0.12727273, 0.3944096 , 0.82352941, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.78181818, 0.07730824, 0.11764706, ..., 0.        , 1.        ,
        0.        ],
       [0.52727273, 0.10157368, 0.11764706, ..., 0.        , 1.        ,
        0.        ],
       [0.30909091, 0.18851106, 0.02941176, ..., 0.        , 0.        ,
        1.        ]])

In [119]:
joblib.dump(column_transformer,'preprocessing.joblib')

['preprocessing.joblib']

## Evaluación de modelos de val cruzada

In [168]:
#versión 1
X_train = train[['Age','Credit amount', 'Duration','Sex','Purpose', 'Housing']]

In [169]:
y_train = train['Risk']

In [170]:
y_train.unique()

array(['good', 'bad'], dtype=object)

In [171]:
X_train_processed = column_transformer.transform(X_train)

In [172]:
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier

In [173]:
y_train_transform = (y_train =='good').astype('int')

In [174]:
result = cross_validate(DecisionTreeClassifier(),
                        X_train_processed, y_train_transform, cv = 10,
                        scoring=["accuracy","f1"])

In [195]:
print(result['test_accuracy'].mean(),'+-',result['test_accuracy'].std() )

0.7214285714285713 +- 0.01317077779613268


In [176]:
##Version 2 
final_pipeline = Pipeline(
    [ 
        ('Pipeline de preprocesamiento', column_transformer),
        ('Modelo de predicción(árbol)',DecisionTreeClassifier(max_depth=3) )
        
    ]
)

In [177]:
result = cross_validate(final_pipeline,
                        X_train, y_train_transform, cv = 10,
                        scoring=["accuracy","f1"])

In [196]:
print(result['test_accuracy'].mean(), '+-',result['test_accuracy'].std() )

0.7214285714285713 +- 0.01317077779613268


In [180]:
from sklearn.model_selection import GridSearchCV

In [181]:
grid={'max_depth':[2,3,5,10]}

In [190]:
grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid = grid, cv=10, scoring= 'accuracy')

In [191]:
grid_search.fit(X_train_processed,y_train_transform)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [2, 3, 5, 10]}, scoring='accuracy')

In [192]:
GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), param_grid={'max_depth':[2,3,9,10]} , scoring=['accuracy'])

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [2, 3, 9, 10]}, scoring=['accuracy'])

In [193]:
grid_search.best_score_

0.7228571428571429

In [194]:
grid_search.best_params_

{'max_depth': 3}